---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: install swatch
    yum: name=swatch state=latest
  - name: put sender script
    template:
      src: send_log.sh
      dest: /usr/local/bin/send_log.sh
      owner: root
      group: root
      mode: 0755
  - name: put swatch-config
    template:
      src: login-watch.conf
      dest: /etc/login-watch.conf
      owner: root
      group: root
      mode: 0644
  - name: put swatchd.sh
    template:
      src: swatchd.sh
      dest: /usr/local/bin/swatchd.sh
      owner: root
      group: root
      mode: 0755
  - name: put service conf
    template:
      src: swatchd.service
      dest: /etc/systemd/system/swatchd.service
      owner: root
      group: root
      mode: 0755
  - name: setup systemd
    service: name=swatchd enabled=yes state=restarted
